packages:
  - software/7zip
  - software/jq
  - catalogue

catalog:
  'turbo': ^2.5.4
  '@changesets/cli': ^2.29.5
  '@platforma-sdk/package-builder': ^3.2.0
  '@platforma-sdk/blocks-deps-updater': '^2.0.0'
